/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author alift
 */
public class CreateRecipePanel extends javax.swing.JPanel {

    private Controller controller;
    /**
     * Creates new form createRecipePanel
     */
    public CreateRecipePanel(Controller controller) {
        initComponents();
        
        this.controller = controller;
        
        Controller.numberOnlySpinner(calSpinner);
        Controller.numberOnlySpinner(proSpinner);
        Controller.numberOnlySpinner(carSpinner);
        Controller.numberOnlySpinner(fatSpinner);
    }

    public JTextArea getIngredientText() { return ingredientText; }
    public JTextField getRecipeNameTextField() { return recipeNameTextField; }
    public JTextArea getStepText() { return stepText; }
    public JTextArea getToolText() { return toolText; }
    public JLabel getWarningLabel() { return warningLabel; }
    public int getCal() { return (int) calSpinner.getValue(); }
    public int getPro() { return (int) proSpinner.getValue(); }
    public int getCar() { return (int) carSpinner.getValue(); }
    public int getFat() { return (int) fatSpinner.getValue(); }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createMealLabel = new javax.swing.JLabel();
        recipeNameLabel = new javax.swing.JLabel();
        recipeNameTextField = new javax.swing.JTextField();
        toolsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toolText = new javax.swing.JTextArea();
        stepsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stepText = new javax.swing.JTextArea();
        caloriesLabel = new javax.swing.JLabel();
        calSpinner = new javax.swing.JSpinner();
        proteinsLabel = new javax.swing.JLabel();
        proSpinner = new javax.swing.JSpinner();
        carboLabels = new javax.swing.JLabel();
        carSpinner = new javax.swing.JSpinner();
        fatsLabel = new javax.swing.JLabel();
        fatSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        ingredientsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ingredientText = new javax.swing.JTextArea();
        warningLabel = new javax.swing.JLabel();

        createMealLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createMealLabel.setText("Create Meal");

        recipeNameLabel.setText("Recipe name:");

        toolsLabel.setText("Tools:");

        toolText.setColumns(20);
        toolText.setRows(5);
        jScrollPane1.setViewportView(toolText);

        stepsLabel.setText("Steps:");

        stepText.setColumns(20);
        stepText.setRows(5);
        jScrollPane2.setViewportView(stepText);

        caloriesLabel.setText("Calories:");

        calSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        proteinsLabel.setText("Proteins:");

        proSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        carboLabels.setText("Carbo:");

        carSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        fatsLabel.setText("Fats:");

        fatSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ingredientsLabel.setText("Ingredients:");

        ingredientText.setColumns(20);
        ingredientText.setRows(5);
        jScrollPane3.setViewportView(ingredientText);

        warningLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warningLabel)
                    .addComponent(ingredientsLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1)
                        .addComponent(stepsLabel)
                        .addComponent(toolsLabel)
                        .addComponent(recipeNameLabel)
                        .addComponent(createMealLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(caloriesLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(calSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(carboLabels))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(proteinsLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(proSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(fatsLabel)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(carSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(recipeNameTextField)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(createMealLabel)
                .addGap(18, 18, 18)
                .addComponent(recipeNameLabel)
                .addGap(0, 0, 0)
                .addComponent(recipeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caloriesLabel)
                    .addComponent(calSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carboLabels)
                    .addComponent(carSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proteinsLabel)
                    .addComponent(proSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatsLabel)
                    .addComponent(fatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ingredientsLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toolsLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stepsLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.createRecipe();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner calSpinner;
    private javax.swing.JLabel caloriesLabel;
    private javax.swing.JSpinner carSpinner;
    private javax.swing.JLabel carboLabels;
    private javax.swing.JLabel createMealLabel;
    private javax.swing.JSpinner fatSpinner;
    private javax.swing.JLabel fatsLabel;
    private javax.swing.JTextArea ingredientText;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner proSpinner;
    private javax.swing.JLabel proteinsLabel;
    private javax.swing.JLabel recipeNameLabel;
    private javax.swing.JTextField recipeNameTextField;
    private javax.swing.JTextArea stepText;
    private javax.swing.JLabel stepsLabel;
    private javax.swing.JTextArea toolText;
    private javax.swing.JLabel toolsLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
