/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.*;

/**
 *
 * @author alift
 */
public class MenuPanel extends javax.swing.JPanel {

    private Controller controller;
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel(Controller controller) {
        this.controller = controller;
        initComponents();
        
        maleRadio.setActionCommand("Male");
        femaleRadio.setActionCommand("Female");
        
        genderGroup = new ButtonGroup();
        genderGroup.add(maleRadio);
        genderGroup.add(femaleRadio);
        
        // Set the editor to allow only numbers
        Controller.numberOnlySpinner(ageSpinner);
        Controller.numberOnlySpinner(heightSpinner);
        Controller.numberOnlySpinner(weightSpinner);
        
        profilePanel.setVisible(false);
        schedulePanel.setVisible(false);
        recipePanel.setVisible(false);
        
        Controller.numberOnlySpinner(ageSpinner);
        Controller.numberOnlySpinner(heightSpinner);
        Controller.numberOnlySpinner(weightSpinner);
        
        mealRecipeDetail.setEditable(false);
        mealScheduleDetail.setEditable(false);
    }

    public JLabel getWelcomeLabel() { return welcomeLabel; }
    public JLabel getCal() { return cal; }
    public JLabel getCarbs() { return carbs; }
    public JLabel getFat() { return fat; }
    public JLabel getPro() { return pro; }
    public JLabel getAgeLabel() { return ageLabel; }
    public JLabel getEmailLabel() { return emailLabel; }
    public JLabel getGenderLabel() { return genderLabel; }
    public JLabel getHeightLabel() { return heightLabel; }
    public JLabel getNameLabel() { return nameLabel; }
    public JLabel getUsernameLabel() { return usernameLabel; }
    public JLabel getWeightLabel() { return weightLabel; }
    public JSpinner getAgeSpinner() { return ageSpinner; }
    public JTextField getEmailTextField() { return emailTextField; }
    public JTextField getNameTextField() { return nameTextField; }
    public int getAge(){ return (int) ageSpinner.getValue(); }
    public int getUserHeight() { return (int) heightSpinner.getValue(); }
    public int getUserWeight() { return (int) weightSpinner.getValue(); }
    public String getGender() { return genderGroup.getSelection().getActionCommand(); }
    public JRadioButton getFemaleRadio() { return femaleRadio; }
    public JRadioButton getMaleRadio() { return maleRadio; }
    public JList<String> getMealRecipeList() { return mealRecipeList; }
    public JTextArea getMealRecipeDetail() { return mealRecipeDetail; } 
    public JTextArea getMealScheduleDetail() { return mealScheduleDetail; } 
    public JList<String> getMealScheduleList() { return mealScheduleList; } 
    public JList<String> getScheduleList() { return scheduleList; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        informationPanel = new javax.swing.JPanel();
        mealPlanLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        cal = new javax.swing.JLabel();
        carbs = new javax.swing.JLabel();
        calLabel = new javax.swing.JLabel();
        proLabel = new javax.swing.JLabel();
        fatLabel = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        pro = new javax.swing.JLabel();
        fat = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        profileMenuPanel = new javax.swing.JPanel();
        profileMenuLabel = new javax.swing.JLabel();
        scheduleMenuPanel = new javax.swing.JPanel();
        scheduleMenuLabel = new javax.swing.JLabel();
        recipeMenuPanel = new javax.swing.JPanel();
        recipeMenuLabel = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        schedulePanel = new javax.swing.JPanel();
        scheduleDetailLabel = new javax.swing.JLabel();
        removeScheduleButton = new javax.swing.JButton();
        addScheduleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleList = new javax.swing.JList<>();
        scheduleListLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mealScheduleList = new javax.swing.JList<>();
        recipeListLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mealScheduleDetail = new javax.swing.JTextArea();
        recipeTextLabel = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profileDetailLabel = new javax.swing.JLabel();
        usernameLabelNoSet = new javax.swing.JLabel();
        genderLabelNoSet = new javax.swing.JLabel();
        emailLabelNoSet = new javax.swing.JLabel();
        heightLabelNoSet = new javax.swing.JLabel();
        ageLabelNoSet = new javax.swing.JLabel();
        weightLabelNoSet = new javax.swing.JLabel();
        nameLabelNoSet = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        ageSpinner = new javax.swing.JSpinner();
        heightSpinner = new javax.swing.JSpinner();
        weightSpinner = new javax.swing.JSpinner();
        cmLabel = new javax.swing.JLabel();
        kgLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        recipePanel = new javax.swing.JPanel();
        recipeDetailLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        mealRecipeDetail = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        mealRecipeList = new javax.swing.JList<>();
        createRecipeButton = new javax.swing.JButton();
        removeRecipeButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(833, 612));

        informationPanel.setBackground(new java.awt.Color(255, 255, 255));

        mealPlanLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mealPlanLabel.setText("MealPlan");

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLabel.setText("Welcome, name!");

        cal.setText("0");

        carbs.setText("0");

        calLabel.setText("Calories:");

        proLabel.setText("Protein:");

        fatLabel.setText("Fat:");

        carLabel.setText("Carbs:");

        pro.setText("0");

        fat.setText("0");

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(mealPlanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 539, Short.MAX_VALUE)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carbs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(mealPlanLabel)
                .addGap(0, 0, 0)
                .addComponent(welcomeLabel)
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calLabel)
                    .addComponent(cal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proLabel)
                    .addComponent(pro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatLabel)
                    .addComponent(fat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carLabel)
                    .addComponent(carbs))
                .addContainerGap())
        );

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setPreferredSize(new java.awt.Dimension(127, 494));

        menuLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuLabel.setText("Menu");

        profileMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        profileMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profileMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMenuPanelMouseClicked(evt);
            }
        });

        profileMenuLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        profileMenuLabel.setText("Profile");

        javax.swing.GroupLayout profileMenuPanelLayout = new javax.swing.GroupLayout(profileMenuPanel);
        profileMenuPanel.setLayout(profileMenuPanelLayout);
        profileMenuPanelLayout.setHorizontalGroup(
            profileMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileMenuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileMenuPanelLayout.setVerticalGroup(
            profileMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileMenuLabel)
                .addContainerGap())
        );

        scheduleMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        scheduleMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scheduleMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleMenuPanelMouseClicked(evt);
            }
        });

        scheduleMenuLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scheduleMenuLabel.setText("Schedule");

        javax.swing.GroupLayout scheduleMenuPanelLayout = new javax.swing.GroupLayout(scheduleMenuPanel);
        scheduleMenuPanel.setLayout(scheduleMenuPanelLayout);
        scheduleMenuPanelLayout.setHorizontalGroup(
            scheduleMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scheduleMenuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scheduleMenuPanelLayout.setVerticalGroup(
            scheduleMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scheduleMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scheduleMenuLabel)
                .addContainerGap())
        );

        recipeMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        recipeMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        recipeMenuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recipeMenuPanelMouseClicked(evt);
            }
        });

        recipeMenuLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recipeMenuLabel.setText("Recipe");

        javax.swing.GroupLayout recipeMenuPanelLayout = new javax.swing.GroupLayout(recipeMenuPanel);
        recipeMenuPanel.setLayout(recipeMenuPanelLayout);
        recipeMenuPanelLayout.setHorizontalGroup(
            recipeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipeMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recipeMenuLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        recipeMenuPanelLayout.setVerticalGroup(
            recipeMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recipeMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recipeMenuLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(menuLabel)
                .addGap(31, 31, 31))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(profileMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scheduleMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recipeMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(menuLabel)
                .addGap(35, 35, 35)
                .addComponent(profileMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scheduleMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(recipeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        detailPanel.setBackground(new java.awt.Color(255, 255, 255));

        schedulePanel.setBackground(new java.awt.Color(255, 255, 255));

        scheduleDetailLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        scheduleDetailLabel.setText("Schedule");

        removeScheduleButton.setText("Remove");
        removeScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeScheduleButtonActionPerformed(evt);
            }
        });

        addScheduleButton.setText("Add");
        addScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScheduleButtonActionPerformed(evt);
            }
        });

        scheduleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scheduleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(scheduleList);

        scheduleListLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scheduleListLabel.setText("Schedule");

        mealScheduleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mealScheduleList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealScheduleListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mealScheduleList);

        recipeListLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recipeListLabel.setText("Recipe");

        mealScheduleDetail.setColumns(20);
        mealScheduleDetail.setRows(5);
        jScrollPane3.setViewportView(mealScheduleDetail);

        recipeTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recipeTextLabel.setText("Recipe Detail");

        javax.swing.GroupLayout schedulePanelLayout = new javax.swing.GroupLayout(schedulePanel);
        schedulePanel.setLayout(schedulePanelLayout);
        schedulePanelLayout.setHorizontalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(schedulePanelLayout.createSequentialGroup()
                                .addComponent(scheduleListLabel)
                                .addGap(84, 84, 84)
                                .addComponent(recipeListLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recipeTextLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(schedulePanelLayout.createSequentialGroup()
                        .addComponent(addScheduleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeScheduleButton))
                    .addComponent(scheduleDetailLabel))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        schedulePanelLayout.setVerticalGroup(
            schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schedulePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(scheduleDetailLabel)
                .addGap(18, 18, 18)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeScheduleButton)
                    .addComponent(addScheduleButton))
                .addGap(18, 18, 18)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scheduleListLabel)
                    .addComponent(recipeListLabel)
                    .addComponent(recipeTextLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));

        profileDetailLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        profileDetailLabel.setText("Profile");

        usernameLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabelNoSet.setText("Username: ");

        genderLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderLabelNoSet.setText("Gender:");

        emailLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabelNoSet.setText("Email:");

        heightLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        heightLabelNoSet.setText("Height:");

        ageLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabelNoSet.setText("Age:");

        weightLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weightLabelNoSet.setText("Weight:");

        nameLabelNoSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabelNoSet.setText("Name: ");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        maleRadio.setText("Male");
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });

        femaleRadio.setText("Female");
        femaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioActionPerformed(evt);
            }
        });

        ageSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        heightSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        weightSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        cmLabel.setText("cm");

        kgLabel.setText("kg");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setText("jLabel1");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLabel.setText("jLabel1");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderLabel.setText("jLabel1");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setText("jLabel1");

        heightLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        heightLabel.setText("jLabel1");

        weightLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weightLabel.setText("jLabel1");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setText("jLabel1");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutButton)
                            .addComponent(profileDetailLabel))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(weightLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weightLabel))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(heightLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heightLabel))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(ageLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ageLabel))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(genderLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderLabel))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(emailLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(usernameLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameLabel))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(nameLabelNoSet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel)))
                        .addGap(48, 48, 48)))
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(emailTextField))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(maleRadio)
                        .addGap(18, 18, 18)
                        .addComponent(femaleRadio))
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmLabel))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(weightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kgLabel))
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(profileDetailLabel)
                .addGap(46, 46, 46)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabelNoSet)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabelNoSet)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelNoSet)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabelNoSet)
                    .addComponent(maleRadio)
                    .addComponent(femaleRadio)
                    .addComponent(genderLabel))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabelNoSet)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabelNoSet)
                    .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmLabel)
                    .addComponent(heightLabel))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLabelNoSet)
                    .addComponent(weightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgLabel)
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(saveButton))
                .addGap(35, 35, 35))
        );

        recipePanel.setBackground(new java.awt.Color(255, 255, 255));

        recipeDetailLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        recipeDetailLabel.setText("Recipe");

        mealRecipeDetail.setColumns(20);
        mealRecipeDetail.setRows(5);
        jScrollPane5.setViewportView(mealRecipeDetail);

        jLabel3.setText("Search");

        jButton5.setText("Search");

        mealRecipeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        mealRecipeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealRecipeListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(mealRecipeList);

        createRecipeButton.setText("Create recipe");
        createRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRecipeButtonActionPerformed(evt);
            }
        });

        removeRecipeButton.setText("Remove recipe");
        removeRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRecipeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recipePanelLayout = new javax.swing.GroupLayout(recipePanel);
        recipePanel.setLayout(recipePanelLayout);
        recipePanelLayout.setHorizontalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addComponent(createRecipeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeRecipeButton))
                    .addComponent(recipeDetailLabel)
                    .addGroup(recipePanelLayout.createSequentialGroup()
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        recipePanelLayout.setVerticalGroup(
            recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(recipeDetailLabel)
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRecipeButton)
                    .addComponent(removeRecipeButton))
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(recipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(schedulePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(recipePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(schedulePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(recipePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profileMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMenuPanelMouseClicked
        schedulePanel.setVisible(false);
        recipePanel.setVisible(false);
        profilePanel.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_profileMenuPanelMouseClicked

    private void scheduleMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleMenuPanelMouseClicked
        profilePanel.setVisible(false);
        recipePanel.setVisible(false);
        schedulePanel.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_scheduleMenuPanelMouseClicked

    private void recipeMenuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recipeMenuPanelMouseClicked
        profilePanel.setVisible(false);
        schedulePanel.setVisible(false);
        recipePanel.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_recipeMenuPanelMouseClicked

    private void addScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScheduleButtonActionPerformed
        controller.showCreateSchedulePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_addScheduleButtonActionPerformed

    private void removeScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeScheduleButtonActionPerformed
        controller.showRemoveSchedulePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_removeScheduleButtonActionPerformed

    private void createRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRecipeButtonActionPerformed
        controller.showCreateRecipePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_createRecipeButtonActionPerformed

    private void removeRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRecipeButtonActionPerformed
        controller.showRemoveRecipePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_removeRecipeButtonActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        femaleRadio.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        maleRadio.setSelected(false);    // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        controller.logout();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        controller.updateProfile();        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void mealRecipeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealRecipeListMouseClicked
        controller.setMealDetail(this.getClass().getSimpleName());          // TODO add your handling code here:
    }//GEN-LAST:event_mealRecipeListMouseClicked

    private void scheduleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleListMouseClicked
        controller.setScheduleMealList();        // TODO add your handling code here:
    }//GEN-LAST:event_scheduleListMouseClicked

    private void mealScheduleListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealScheduleListMouseClicked
        controller.setScheduleMealDetail();        // TODO add your handling code here:
    }//GEN-LAST:event_mealScheduleListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addScheduleButton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabelNoSet;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JLabel cal;
    private javax.swing.JLabel calLabel;
    private javax.swing.JLabel carLabel;
    private javax.swing.JLabel carbs;
    private javax.swing.JLabel cmLabel;
    private javax.swing.JButton createRecipeButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabelNoSet;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel fat;
    private javax.swing.JLabel fatLabel;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabelNoSet;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel heightLabelNoSet;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JLabel mealPlanLabel;
    private javax.swing.JTextArea mealRecipeDetail;
    private javax.swing.JList<String> mealRecipeList;
    private javax.swing.JTextArea mealScheduleDetail;
    private javax.swing.JList<String> mealScheduleList;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabelNoSet;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel pro;
    private javax.swing.JLabel proLabel;
    private javax.swing.JLabel profileDetailLabel;
    private javax.swing.JLabel profileMenuLabel;
    private javax.swing.JPanel profileMenuPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel recipeDetailLabel;
    private javax.swing.JLabel recipeListLabel;
    private javax.swing.JLabel recipeMenuLabel;
    private javax.swing.JPanel recipeMenuPanel;
    private javax.swing.JPanel recipePanel;
    private javax.swing.JLabel recipeTextLabel;
    private javax.swing.JButton removeRecipeButton;
    private javax.swing.JButton removeScheduleButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel scheduleDetailLabel;
    private javax.swing.JList<String> scheduleList;
    private javax.swing.JLabel scheduleListLabel;
    private javax.swing.JLabel scheduleMenuLabel;
    private javax.swing.JPanel scheduleMenuPanel;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabelNoSet;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightLabelNoSet;
    private javax.swing.JSpinner weightSpinner;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
