/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author alift
 */
public class RemoveSchedulePanel extends javax.swing.JPanel {

    Controller controller;
    /**
     * Creates new form RemoveSchedulePanel
     */
    public RemoveSchedulePanel(Controller controller) {
        this.controller = controller;
        initComponents();
        
        Controller.numberOnlySpinner(daySpinner);
        Controller.numberOnlySpinner(monthSpinner);
        Controller.numberOnlySpinner(yearSpinner);
        
        mealList.setModel(null);
        mealDetail.setEditable(false);
    }

    public int getDay(){ return (int) daySpinner.getValue(); }
    public int getMonth() { return (int) monthSpinner.getValue(); }
    public int getYear() { return (int) yearSpinner.getValue(); }
    public JTextArea getMealDetail() { return mealDetail; }
    public JList<String> getMealList() { return mealList; }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeScheduleLabel = new javax.swing.JLabel();
        yearSpinner = new javax.swing.JSpinner();
        dateLabel = new javax.swing.JLabel();
        mealLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealList = new javax.swing.JList<>();
        dayLabel = new javax.swing.JLabel();
        daySpinner = new javax.swing.JSpinner();
        monthLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mealDetail = new javax.swing.JTextArea();
        monthSpinner = new javax.swing.JSpinner();
        yearLabel = new javax.swing.JLabel();
        removeScheduleButton = new javax.swing.JButton();
        removeRecipeButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        removeScheduleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removeScheduleLabel.setText("Remove Schedule");

        yearSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateLabel.setText("Date");

        mealLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mealLabel.setText("Meal");

        mealList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(mealList);

        dayLabel.setText("Day:");

        daySpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        monthLabel.setText("Month:");

        mealDetail.setColumns(20);
        mealDetail.setRows(5);
        jScrollPane2.setViewportView(mealDetail);

        monthSpinner.setPreferredSize(new java.awt.Dimension(65, 22));

        yearLabel.setText("Year:");

        removeScheduleButton.setText("Remove schedule");

        removeRecipeButton.setText("Remove recipe");

        refreshButton.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeScheduleButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeRecipeButton))
                    .addComponent(mealLabel)
                    .addComponent(dateLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yearLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(removeScheduleLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(removeScheduleLabel)
                .addGap(18, 18, 18)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayLabel)
                    .addComponent(monthLabel)
                    .addComponent(monthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLabel)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(mealLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeScheduleButton)
                    .addComponent(removeRecipeButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JSpinner daySpinner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mealDetail;
    private javax.swing.JLabel mealLabel;
    private javax.swing.JList<String> mealList;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JSpinner monthSpinner;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton removeRecipeButton;
    private javax.swing.JButton removeScheduleButton;
    private javax.swing.JLabel removeScheduleLabel;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
