/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author alift
 */
public class RemoveRecipePanel extends javax.swing.JPanel {

    private Controller controller;
    /**
     * Creates new form removeRecipePanel
     */
    public RemoveRecipePanel(Controller controller) {
        this.controller = controller;
        
        initComponents();
    }

    public JTextArea getMealDetailText() { return mealDetailText; }
    public JList<String> getMealList() { return mealList; }
    public JLabel getWarningLabel() { return warningLabel; }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeMealLabel = new javax.swing.JLabel();
        mealLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        mealDetailText = new javax.swing.JTextArea();
        removeButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        removeMealLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        removeMealLabel.setText("Remove meal");

        mealLabel.setText("Meal");

        mealList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mealListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mealList);

        mealDetailText.setColumns(20);
        mealDetailText.setRows(5);
        jScrollPane2.setViewportView(mealDetailText);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        warningLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warningLabel)
                    .addComponent(removeButton)
                    .addComponent(mealLabel)
                    .addComponent(removeMealLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(removeMealLabel)
                .addGap(18, 18, 18)
                .addComponent(mealLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(warningLabel)
                .addGap(0, 0, 0)
                .addComponent(removeButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mealListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mealListMouseClicked
        controller.setMealDetail(this.getClass().getSimpleName());        // TODO add your handling code here:
    }//GEN-LAST:event_mealListMouseClicked

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        controller.removeRecipe();        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mealDetailText;
    private javax.swing.JLabel mealLabel;
    private javax.swing.JList<String> mealList;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel removeMealLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
